"""DOCSUP-01 adversarial-input table for the doc-dependency registry loader.

The phase's anti-pattern fence: every control-shaped change gets its adversarial table authored
FIRST and shown RED against pre-fix code FOR THE STATED REASON. Both tables below were run against
a SHAPE-ONLY validator (``tomllib.load`` + ``Draft202012Validator``, no semantic rules) before any
rejection landed — ``REJECTION_CASES`` red with "DID NOT RAISE", ``VALID_CASES`` green. The verbatim
output is recorded in ``28-03-SUMMARY.md``.

Two tables, and BOTH are load-bearing:

``REJECTION_CASES``
    One row per DOCSUP-01 rejection class plus its spelling variants. Every row is shape-VALID
    against ``contracts/harness/docs/doc-dependencies.schema.json`` on purpose — a row the schema
    already catches proves nothing about this module's controls.

``VALID_CASES``
    The negative control. A guard that refuses everything passes every rejection test, so
    "did not over-refuse" needs its own pinned table: a ``contracts/**`` SOURCE (the row proving
    ``refuse_unsafe_destination`` was NOT reused), a ``..`` SUBSTRING that is not a segment, an
    ``advisory`` row with empty ``sources``, and an accepted ADR with the forced disposition pair.

Class D is GENERATED by iterating the IMPORTED ``DERIVED_GLOBS`` — hardcoding a second copy is
exactly the defect that class exists to prevent.
"""

from __future__ import annotations

import builtins
from pathlib import Path

import pytest

from tools.adoption_scan.destinations import DERIVED_GLOBS
from tools.docs_guard import registry

# ── Reason fragments each rejection's message must carry ────────────────────────────────────────
# The message is what teaches the operator the fix, so the class is asserted, not merely "raised".
ESC = "path escape"
DUP = "duplicate binding id"
EMPTY = "empty sources on a required binding"
DERIVED = "derived target"
ADR_PAIR = "accepted-ADR disposition pair"
ADR_PROPOSED = "not an accepted ADR"
ADR_VOCAB = "ADR-only disposition"
CONTROL = "forbidden character"

# The forced pair for a docs/adr/** target (D-09). Order is irrelevant to the rule; the SET is not.
ADR_PAIR_VALUE = ["REVIEWED_STILL_CURRENT", "SUPERSEDING_ADR_REQUIRED"]

# Substituted with the tmp root's POSIX path at parametrize time, so no literal system path (and no
# host-specific absolute spelling) is ever baked into the table.
ROOT_TOKEN = "{ROOT}"

# Appears in exactly one row's payload and is never part of a diagnostic's legitimate vocabulary —
# the no-content-leak probe (a hostile registry may carry arbitrary bytes).
LEAK_MARKER = "zz-leak-canary-zz"


def _row(
    *,
    id: str = "binding-one",
    sources: list[str] | None = None,
    target: str = "docs/how-to/x.md",
    severity: str = "required",
    dispositions: list[str] | None = None,
) -> str:
    """Render one shape-valid ``[[binding]]`` table."""
    sources = ["src/one.py"] if sources is None else sources
    dispositions = ["updated", "reviewed-no-change"] if dispositions is None else dispositions
    return (
        "[[binding]]\n"
        f"id = {id!r}\n"
        f"sources = [{', '.join(repr(s) for s in sources)}]\n"
        f"target = {target!r}\n"
        f"severity = {severity!r}\n"
        f"dispositions = [{', '.join(repr(d) for d in dispositions)}]\n"
    ).replace("'", '"')


def _reg(*rows: str) -> str:
    return "\n".join(rows)


def _derived_target(glob: str) -> str:
    """A concrete file path that ``glob`` admits — ``docs/reference/**`` -> ``docs/reference/x.md``,
    a literal entry like ``opencode.json`` is already a file path."""
    return f"{glob[:-3]}/x.md" if glob.endswith("/**") else glob


# ── Class A — path escape (refused BEFORE any filesystem call) ──────────────────────────────────
CLASS_A: list[tuple[str, str, str]] = [
    ("source_absolute", _reg(_row(sources=[f"{ROOT_TOKEN}/../outside/secret.md"])), ESC),
    ("source_dotdot", _reg(_row(sources=["docs/../../etc/passwd"])), ESC),
    ("target_absolute", _reg(_row(target=f"{ROOT_TOKEN}/../outside/secret.md")), ESC),
    ("target_dotdot", _reg(_row(target="docs/../../etc/passwd")), ESC),
    # Structurally innocent — only resolve-then-confine can catch it (the backstop).
    ("source_symlink_escape", _reg(_row(sources=["docs/escape-link/secret.md"])), ESC),
]

# ── Class B — duplicate id ──────────────────────────────────────────────────────────────────────
CLASS_B: list[tuple[str, str, str]] = [
    (
        "duplicate_id",
        _reg(_row(id="binding-one"), _row(id="binding-one", target="docs/how-to/y.md")),
        DUP,
    ),
]

# ── Class C — empty selector on a required binding (conditional, hence not `minItems`) ──────────
CLASS_C: list[tuple[str, str, str]] = [
    ("required_empty_sources", _reg(_row(severity="required", sources=[])), EMPTY),
]

# ── Class D — derived/reference target, GENERATED from the imported DERIVED_GLOBS ───────────────
# Iterated, never retyped: if destinations.py grows an entry, this table grows with it. A hardcoded
# copy would silently disagree with the destination catalog — the very defect T-28-12 names.
CLASS_D: list[tuple[str, str, str]] = [
    (
        f"derived_target_{_derived_target(glob).replace('/', '_').replace('.', '_')}",
        _reg(_row(target=_derived_target(glob))),
        DERIVED,
    )
    for glob in DERIVED_GLOBS
]

# ── Class E — accepted-ADR edit policy (D-09) ───────────────────────────────────────────────────
_ACCEPTED_ADR = "docs/adr/0009-accepted.md"
_PROPOSED_ADR = "docs/adr/0099-proposed.md"

CLASS_E: list[tuple[str, str, str]] = [
    (
        "adr_target_with_updated",
        _reg(_row(target=_ACCEPTED_ADR, dispositions=["updated", "REVIEWED_STILL_CURRENT"])),
        ADR_PAIR,
    ),
    (
        "adr_target_default_dispositions",
        _reg(_row(target=_ACCEPTED_ADR, dispositions=["updated", "reviewed-no-change"])),
        ADR_PAIR,
    ),
    (
        "adr_target_partial",
        _reg(_row(target=_ACCEPTED_ADR, dispositions=["REVIEWED_STILL_CURRENT"])),
        ADR_PAIR,
    ),
    (
        "adr_target_extra",
        _reg(_row(target=_ACCEPTED_ADR, dispositions=[*ADR_PAIR_VALUE, "updated"])),
        ADR_PAIR,
    ),
    (
        "adr_target_proposed_status",
        _reg(_row(target=_PROPOSED_ADR, dispositions=ADR_PAIR_VALUE)),
        ADR_PROPOSED,
    ),
    # The partition is two-way: a non-ADR target must not borrow the ADR vocabulary either, or
    # Phase 29's /docs-update filter loses its structural split.
    (
        "non_adr_target_with_adr_dispositions",
        _reg(_row(target="docs/how-to/x.md", dispositions=ADR_PAIR_VALUE)),
        ADR_VOCAB,
    ),
]

# ── Class F — control characters and the table separator in a selector (WR-02) ─────────────────
# The registry is agent-writable BY DESIGN (DOCSUP-07) and its `target` flows unescaped into the
# derived queue's markdown table, whose row count the SessionStart pointer reports. A TOML
# multi-line basic string permits a real newline, so a single `target` could forge extra rows into
# the queue and inflate the pointer. Rejected at the source here; `docs_staleness.render` also
# neutralizes defensively, because a renderer that can be made to emit a forged row is a renderer
# bug no matter who validated the input.
CLASS_F: list[tuple[str, str, str]] = [
    ("target_newline", _reg(_row(target="docs/how-to/x.md\n| FAKE | f | BROKEN |")), CONTROL),
    ("target_carriage_return", _reg(_row(target="docs/how-to/x.md\r| FAKE |")), CONTROL),
    ("target_pipe", _reg(_row(target="docs/how-to/x|y.md")), CONTROL),
    ("target_tab", _reg(_row(target="docs/how-to/x\ty.md")), CONTROL),
    ("source_newline", _reg(_row(sources=["src/one.py\n| FAKE |"])), CONTROL),
    ("source_pipe", _reg(_row(sources=["src/one|two.py"])), CONTROL),
]

REJECTION_CASES: list[tuple[str, str, str]] = [
    *CLASS_A,
    *CLASS_B,
    *CLASS_C,
    *CLASS_D,
    *CLASS_E,
    *CLASS_F,
]

# ── Negative control — none of these may be refused ─────────────────────────────────────────────
# ``None`` payload == "do not write the registry file at all": missing is not invalid (it yields
# zero bindings, so plans 28-05/28-06 can land before the seed data of plan 28-07).
VALID_CASES: list[tuple[str, str | None]] = [
    ("plain_how_to_target", _reg(_row())),
    # Proves refuse_unsafe_destination was NOT reused: it refuses contracts/**, but a contract
    # schema is a legitimate registry SOURCE.
    (
        "contracts_source",
        _reg(_row(sources=["contracts/harness/docs/doc-dependencies.schema.json"])),
    ),
    # ".." as a SUBSTRING, not a path SEGMENT — a structural check that greps for ".." over-refuses.
    ("dotdot_substring_not_segment", _reg(_row(sources=["libs/python/a..b.py"]))),
    ("advisory_empty_sources", _reg(_row(severity="advisory", sources=[]))),
    ("accepted_adr_forced_pair", _reg(_row(target=_ACCEPTED_ADR, dispositions=ADR_PAIR_VALUE))),
    ("missing_registry_file", None),
]


@pytest.fixture
def registry_root(tmp_path: Path) -> Path:
    """A tmp tree carrying every path the two tables reference, plus one real escaping symlink."""
    root = tmp_path / "repo"
    for relative in (
        "docs/how-to/x.md",
        "docs/how-to/y.md",
        "src/one.py",
        "libs/python/a..b.py",
        "contracts/harness/docs/doc-dependencies.schema.json",
    ):
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("seed\n", encoding="utf-8")

    adr_dir = root / "docs" / "adr"
    adr_dir.mkdir(parents=True, exist_ok=True)
    (adr_dir / "0009-accepted.md").write_text(
        "# 9. Accepted\n\n- **Status:** accepted\n", encoding="utf-8"
    )
    (adr_dir / "0099-proposed.md").write_text(
        "# 99. Proposed\n\n- **Status:** proposed\n", encoding="utf-8"
    )

    outside = tmp_path / "outside"
    outside.mkdir()
    (outside / "secret.md").write_text("secret\n", encoding="utf-8")
    (root / "docs" / "escape-link").symlink_to(outside, target_is_directory=True)

    return root


def _write_registry(root: Path, text: str | None) -> Path:
    """Materialize a case's registry under ``root``, returning its path (unwritten if ``None``)."""
    path = root / "docs" / "doc-dependencies.toml"
    if text is not None:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text.replace(ROOT_TOKEN, root.as_posix()), encoding="utf-8")
    return path


@pytest.mark.parametrize(
    ("case_name", "toml_text", "expected_reason"),
    REJECTION_CASES,
    ids=[case[0] for case in REJECTION_CASES],
)
def test_rejection_case(registry_root: Path, case_name: str, toml_text: str, expected_reason: str):
    """Every DOCSUP-01 adversarial row raises ``RegistryError`` FOR ITS STATED REASON."""
    path = _write_registry(registry_root, toml_text)

    with pytest.raises(registry.RegistryError) as excinfo:
        registry.load_registry(path=path, root=registry_root)

    message = str(excinfo.value)
    assert expected_reason in message, f"{case_name}: wrong rejection class -> {message}"
    # A hostile registry may carry arbitrary bytes; a diagnostic must never echo the file back.
    assert path.read_text(encoding="utf-8") not in message


def test_registry_error_is_value_error():
    """Callers (plan 28-05's CLI) catch ``ValueError`` — the subclass relation is load-bearing."""
    assert issubclass(registry.RegistryError, ValueError)


@pytest.mark.parametrize(
    ("case_name", "toml_text"), VALID_CASES, ids=[case[0] for case in VALID_CASES]
)
def test_valid_case(registry_root: Path, case_name: str, toml_text: str | None):
    """The negative control: the guard must not over-refuse anything legitimate."""
    path = _write_registry(registry_root, toml_text)

    bindings = registry.load_registry(path=path, root=registry_root)

    assert isinstance(bindings, list)
    assert bindings == [] if toml_text is None else len(bindings) == 1


@pytest.mark.parametrize(
    ("case_name", "toml_text", "expected_reason"),
    CLASS_A,
    ids=[case[0] for case in CLASS_A],
)
def test_class_a_reads_nothing_outside_root(
    registry_root: Path, monkeypatch, case_name: str, toml_text: str, expected_reason: str
):
    """Zero-call spy proof: the escaping path is never opened or read.

    The registry file ITSELF is legitimately opened, so the spy counts only calls naming a path
    outside the tmp root — the structural pre-check (and, for the symlink row, resolve-then-confine)
    must fire before any such read.
    """
    path = _write_registry(registry_root, toml_text)
    outside = registry_root.parent / "outside"
    read_paths: list[str] = []

    # Hand-rolled wrappers, not ``MagicMock(wraps=...)``: patching an UNBOUND method on ``Path``
    # with a mock drops ``self``, so the spy itself would fail rather than observe anything.
    original_open = builtins.open
    original_path_open = Path.open
    original_read_bytes = Path.read_bytes
    original_read_text = Path.read_text

    def spy_open(file, *args, **kwargs):
        read_paths.append(str(file))
        return original_open(file, *args, **kwargs)

    def spy_path_open(self, *args, **kwargs):
        read_paths.append(str(self))
        return original_path_open(self, *args, **kwargs)

    def spy_read_bytes(self, *args, **kwargs):
        read_paths.append(str(self))
        return original_read_bytes(self, *args, **kwargs)

    def spy_read_text(self, *args, **kwargs):
        read_paths.append(str(self))
        return original_read_text(self, *args, **kwargs)

    monkeypatch.setattr(builtins, "open", spy_open)
    monkeypatch.setattr(Path, "open", spy_path_open)
    monkeypatch.setattr(Path, "read_bytes", spy_read_bytes)
    monkeypatch.setattr(Path, "read_text", spy_read_text)

    with pytest.raises(registry.RegistryError):
        registry.load_registry(path=path, root=registry_root)

    monkeypatch.undo()
    assert [read for read in read_paths if str(outside) in read] == []
    assert [read for read in read_paths if "etc/passwd" in read] == []
    # The registry file itself IS legitimately read — a spy that observed nothing at all would
    # pass vacuously and prove nothing about the escaping path.
    assert str(path) in read_paths


def test_duplicate_id_diagnostic_is_deterministically_sorted(registry_root: Path):
    """Two duplicated ids, authored in reverse order: the diagnostic must be SORTED, not incidental.

    Mirrors ``tools/harness_config/loader.py:149-160``. A gate whose message ordering varies across
    runs is not reviewable, and a single-duplicate assertion cannot tell sorted from lucky.
    """
    path = _write_registry(
        registry_root,
        _reg(
            _row(id="zulu-binding"),
            _row(id="zulu-binding", target="docs/how-to/y.md"),
            _row(id="alpha-binding", target="docs/how-to/x.md"),
            _row(id="alpha-binding", target="docs/how-to/y.md"),
        ),
    )

    with pytest.raises(registry.RegistryError) as excinfo:
        registry.load_registry(path=path, root=registry_root)

    assert "alpha-binding, zulu-binding" in str(excinfo.value)


def test_class_d_rows_track_the_imported_glob_list():
    """Class D is generated from the imported catalog, so it cannot fall out of date."""
    assert len(CLASS_D) == len(DERIVED_GLOBS)
    assert registry.DERIVED_GLOBS is DERIVED_GLOBS


def test_diagnostic_never_leaks_file_content(registry_root: Path):
    """A rejection names the offending id/path only — never the registry's bytes (T-28-14)."""
    path = _write_registry(
        registry_root,
        _reg(
            _row(id="binding-one", sources=["docs/../../etc/passwd"]),
            _row(id="binding-two", sources=[f"docs/how-to/{LEAK_MARKER}.md"]),
        ),
    )

    with pytest.raises(registry.RegistryError) as excinfo:
        registry.load_registry(path=path, root=registry_root)

    assert LEAK_MARKER not in str(excinfo.value)


def test_load_registry_writes_nothing(registry_root: Path):
    """``load_registry`` is read-only — plan 28-05's exit-3 path must not mutate the tree."""
    path = _write_registry(registry_root, _reg(_row()))
    before = sorted(p.relative_to(registry_root).as_posix() for p in registry_root.rglob("*"))

    registry.load_registry(path=path, root=registry_root)

    assert (
        sorted(p.relative_to(registry_root).as_posix() for p in registry_root.rglob("*")) == before
    )
