"""Import-path wiring + THE single synthetic mini-repo fixture for adoption_scan tests (D-06).

adoption_scan is a virtual uv-workspace member (not pip-installed), imported by module path
from the repo root. The tests must put the repo root onto sys.path themselves so that
``from tools.adoption_scan import scan, detect`` resolves. Mirrors
``tools/harness_config/tests/conftest.py`` exactly for the import-path wiring.

``tmp_minirepo`` materializes THE one synthetic target tree (D-06 — no fixture proliferation,
v2.3 FINAL §152) that embeds every exclusion/detection case named by the plan (a)-(o):
secret-by-path, secret-by-content, binary, vendored, generated, over-cap (size-capped),
source-dump (both the over-cap+segment reading and the under-cap banner-marker reading), a
hash-equal collision pair plus its hash-different counterpart (consumed by Plan 03), an
ambiguous/extensionless file, an escaping symlink, a manifest, a CI surface, a test surface, an
ADR surface, and a marker-capable root AGENTS.md. This same tree seeds Phase 27's future
application fixtures. Domain-neutral vocabulary only (widget/source/sink — never
log-parser/dotnet/semiconductor terms, per GEN-04/Pitfall 4).

``tmp_pnpm_workspace`` (52-02, OBS-D-01) is a SECOND, additive fixture — the one deliberate
exception to D-06's single-fixture rule. ``tmp_minirepo`` must stay byte-identical (D-10: the
committed ``test_snapshots.py`` syrupy snapshot proves the no-workspace-manifest discovery path
is unchanged), which would be impossible if the pnpm-workspace case were bolted onto the same
tree — any addition to ``tmp_minirepo`` moves that snapshot. So the pnpm case gets its own
tree instead of touching the D-06 fixture at all.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

# tests -> adoption_scan -> tools -> repo root (parents[3]; mirrors harness_config/tests/conftest)
_REPO_ROOT = Path(__file__).resolve().parents[3]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


@pytest.fixture(scope="session")
def repo_root() -> Path:
    """The repository root."""
    return _REPO_ROOT


@pytest.fixture()
def tmp_minirepo(tmp_path: Path) -> Path:
    """THE single synthetic mini-repo tree (D-06), embedding every exclusion/detection case.

    Every path and identifier is domain-neutral (widget/source/sink vocabulary only).
    """
    root = tmp_path / "minirepo"
    root.mkdir()

    # (a) secret-by-path: a `.env` file (SECRET_PATH_GLOBS `*.env`).
    (root / ".env").write_text("DB_PASS=doesnotmatter\n", encoding="utf-8")

    # (b) secret-by-content: NOT named .env, matches a SECRET_CONTENT_PATTERNS regex
    # (the AKIA[0-9A-Z]{16} AWS-access-key shape) — 16 chars after AKIA. Built by concatenation
    # so this fixture's own source text never carries a contiguous secret-shaped literal.
    sink_dir = root / "sink"
    sink_dir.mkdir()
    _fixture_aws_key = "AKIA" + "ABCDEFGHIJKLMNOP"
    (sink_dir / "secret_config.py").write_text(
        f'AWS_KEY = "{_fixture_aws_key}"\n', encoding="utf-8"
    )

    # (c) binary: leading NUL bytes.
    (root / "binary.dat").write_bytes(b"\x00\x01\x02BINARY\x00\x03\x04" + b"\x00" * 16)

    # (d) vendored: a node_modules/ directory.
    vendored_dir = root / "node_modules" / "pkg"
    vendored_dir.mkdir(parents=True)
    (vendored_dir / "index.js").write_text("module.exports = {};\n", encoding="utf-8")

    # (e) generated: first line carries a @generated marker (not a path/suffix denylist hit).
    (root / "generated.py").write_text(
        "# @generated — do not edit\nprint('hello')\n", encoding="utf-8"
    )

    # (f) over-cap file (>256 KiB), no dump/snapshot/backup path segment -> size-capped, not
    # source-dump.
    assets_dir = root / "assets"
    assets_dir.mkdir()
    (assets_dir / "oversized.dat").write_bytes(b"x" * (300 * 1024))

    # (g1) source-dump reading (b): over-cap AND a `dump`/`snapshot`/`backup` path segment.
    backups_dir = root / "backups"
    backups_dir.mkdir()
    (backups_dir / "repo-dump.txt").write_bytes(b"y" * (300 * 1024))

    # (g2) source-dump reading (a): UNDER the size cap, excluded purely by the first-2KiB
    # repomix-style concatenation banner marker (path carries no dump/snapshot/backup segment).
    notes_dir = root / "notes"
    notes_dir.mkdir()
    (notes_dir / "full-context.txt").write_text(
        "This file is a merged representation of the entire codebase, combined into a single "
        "document generated by repomix.\n\n# File: source/widget.py\ndef widget(): ...\n",
        encoding="utf-8",
    )

    # (h) hash-equal collision pair (widget_a.py == widget_b.py) PLUS the hash-different
    # counterpart widget_a_modified.py (Plan 03's preserve vs conflict disposition fixtures).
    widget_a_content = 'def widget():\n    return "source"\n'
    (root / "widget_a.py").write_text(widget_a_content, encoding="utf-8")
    (root / "widget_b.py").write_text(widget_a_content, encoding="utf-8")
    (root / "widget_a_modified.py").write_text(
        'def widget():\n    return "sink"\n', encoding="utf-8"
    )

    # (i) extensionless/ambiguous file.
    (root / "README").write_text("# Mini Repo\n", encoding="utf-8")

    # (j) a symlink escaping the tree — never followed, recorded as symlink-escape.
    try:
        (root / "escape").symlink_to("/etc/passwd")
    except OSError:
        pytest.skip("unprivileged symlink creation is not permitted on this filesystem")

    # (k) a pyproject.toml manifest.
    (root / "pyproject.toml").write_text('[project]\nname = "widget"\n', encoding="utf-8")

    # (l) a CI surface. The trailing comment line mirrors this repo's own real SC-1
    # false-positive shape (a short, benign TOKEN:-style comment value) — built by
    # concatenation per this file's own (b) convention so the source never carries a
    # contiguous secret-shaped literal.
    workflows_dir = root / ".github" / "workflows"
    workflows_dir.mkdir(parents=True)
    _fixture_token_comment = "# Least-privilege GITHUB_" + "TOKEN: gate jobs read, never write.\n"
    (workflows_dir / "ci.yml").write_text(
        "name: test\non: [push]\njobs: {}\n" + _fixture_token_comment, encoding="utf-8"
    )

    # (m) a test surface.
    tests_dir = root / "tests"
    tests_dir.mkdir()
    (tests_dir / "test_widget.py").write_text("def test_widget():\n    pass\n", encoding="utf-8")

    # (n) an ADR surface.
    adr_dir = root / "docs" / "adr"
    adr_dir.mkdir(parents=True)
    (adr_dir / "0001-decision.md").write_text("# Decision\n", encoding="utf-8")

    # (o) root AGENTS.md carrying the literal harness BEGIN/END HARNESS-MANAGED markers
    # (marker-capable surface, consumed by Plan 03) — must stay INCLUDED, never "generated".
    (root / "AGENTS.md").write_text(
        "<!-- BEGIN HARNESS-MANAGED (generated by tools.harness_emit — do not hand-edit) -->\n"
        "<!-- END HARNESS-MANAGED -->\n",
        encoding="utf-8",
    )

    # (p) a schema surface UNDER contracts/.
    contracts_dir = root / "contracts"
    contracts_dir.mkdir()
    (contracts_dir / "widget.schema.json").write_text('{"type": "object"}\n', encoding="utf-8")

    # (q) a CODEOWNERS surface.
    (workflows_dir.parent / "CODEOWNERS").write_text("* @nobody\n", encoding="utf-8")

    # (r) a schema-LOOKING file OUTSIDE contracts/ — the WARNING 2 negative-match case, proving
    # detect_schema_surfaces() does NOT match it.
    tools_dir = root / "tools"
    tools_dir.mkdir()
    (tools_dir / "widget_tool.schema.json").write_text('{"type": "object"}\n', encoding="utf-8")

    return root


@pytest.fixture()
def tmp_pnpm_workspace(tmp_path: Path) -> Path:
    """A SECOND, additive synthetic tree (52-02, OBS-D-01) — a pnpm workspace with a declared
    ``packages:`` glob list, four members, and one non-member manifest outside those globs
    (the neutral analogue of the Phase-51 ``docs/design-prototype/package.json`` symptom).

    Does NOT modify ``tmp_minirepo`` in any way — see the module docstring for why this fixture
    exists separately. Domain-neutral vocabulary only (widget/source/sink) — never a real-target
    scoped name or an org-specific package-scope prefix (GEN-04).
    """
    root = tmp_path / "pnpm-workspace"
    root.mkdir()

    # The workspace manifest: two bare glob entries, no negation, no `**` (D-09/NG-01 — mirrors
    # exactly the real target's shape, 52-RESEARCH.md, read live 2026-07-31).
    (root / "pnpm-workspace.yaml").write_text(
        'packages:\n  - "apps/*"\n  - "packages/*"\n', encoding="utf-8"
    )

    # Root package.json (the implicit workspace-root member).
    (root / "package.json").write_text(
        json.dumps(
            {
                "name": "widget-workspace",
                "private": True,
                "scripts": {"lint": "eslint .", "test": "vitest run", "format": "prettier -w ."},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (root / ".gitignore").write_text("node_modules/\n", encoding="utf-8")

    # Four declared members (apps/*, packages/*), mirroring the real target's five (root + 4).
    apps_dir = root / "apps"
    packages_dir = root / "packages"

    widget_app_dir = apps_dir / "widget-app"
    widget_app_dir.mkdir(parents=True)
    (widget_app_dir / "package.json").write_text(
        json.dumps(
            {
                "name": "widget-app",
                "private": True,
                "dependencies": {"@widget/shared": "workspace:*"},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (widget_app_dir / "index.js").write_text("console.log('widget-app');\n", encoding="utf-8")

    widget_service_dir = apps_dir / "widget-service"
    widget_service_dir.mkdir(parents=True)
    (widget_service_dir / "package.json").write_text(
        json.dumps(
            {
                "name": "widget-service",
                "private": True,
                "dependencies": {"@widget/shared": "workspace:*"},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    (widget_service_dir / "index.js").write_text(
        "console.log('widget-service');\n", encoding="utf-8"
    )

    widget_shared_dir = packages_dir / "widget-shared"
    widget_shared_dir.mkdir(parents=True)
    (widget_shared_dir / "package.json").write_text(
        json.dumps({"name": "@widget/shared", "private": True}, indent=2) + "\n",
        encoding="utf-8",
    )
    (widget_shared_dir / "index.js").write_text("module.exports = {};\n", encoding="utf-8")

    widget_ui_dir = packages_dir / "widget-ui"
    widget_ui_dir.mkdir(parents=True)
    (widget_ui_dir / "package.json").write_text(
        json.dumps({"name": "widget-ui", "private": True}, indent=2) + "\n",
        encoding="utf-8",
    )
    (widget_ui_dir / "index.js").write_text("module.exports = {};\n", encoding="utf-8")

    # ONE non-member manifest — the neutral analogue of the Phase-51 symptom
    # (docs/design-prototype/package.json).
    design_prototype_dir = root / "docs" / "design-prototype"
    design_prototype_dir.mkdir(parents=True)
    (design_prototype_dir / "package.json").write_text(
        json.dumps({"name": "design-prototype", "private": True}, indent=2) + "\n",
        encoding="utf-8",
    )
    (design_prototype_dir / "README.md").write_text(
        "# Design Prototype\n\nNot a workspace member.\n", encoding="utf-8"
    )

    return root
