"""Emit spine — read harness/ source → validate → project → write both runtime trees (EMIT-02).

Clones the ``tools/docs_sync/generate.py`` determinism discipline: a repo-root anchor, a typed
loud-fail error (mirror ``DocsSyncError``), a VERBATIM ``_confine`` traversal guard called before
every write, LF/no-BOM UTF-8 output, a DERIVED "do not hand-edit" marker, and NO
``datetime.now()``/timestamps/floats — so a second emit reproduces every file byte-for-byte (the CI
``emit-drift`` gate depends on it).

Frontmatter is re-serialized from a FIXED ordered template per target (NOT a ruamel round-trip,
which can reorder/reflow and flap the drift gate). The ``permission.bash`` sub-object keeps its
AUTHORED insertion order — that order is semantic last-wins, ``*``-first (Pitfall P3).

Wave-1 (D-05) emits ONLY the 4 harness agents to ``.opencode/agent/`` + ``.claude/agents/`` and
writes the ownership manifest; commands/skills/plugins/config widen this spine in later waves.

Entrypoint: ``python -m tools.harness_emit``.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

from tools.harness_emit import (
    manifest,
    permissions,
    project_agent,
    project_command,
    project_skill,
    validate,
)
from tools.harness_lint import parse_frontmatter
from tools.harness_perms.resolver import load_matrix

# --- paths (tools/harness_emit/generate.py → parents[2] == repo root) -------------------------
REPO_ROOT = Path(__file__).resolve().parents[2]
HARNESS_DIR = REPO_ROOT / "harness"
OPENCODE_DIR = REPO_ROOT / ".opencode"
CLAUDE_DIR = REPO_ROOT / ".claude"
MANIFEST_PATH = REPO_ROOT / "tools" / "harness_emit" / "emit-manifest.json"

# The DERIVED marker — the FIRST line inside the frontmatter fence (a YAML comment, so the file's
# first line stays ``---`` and the runtime frontmatter parsers still load it). "do not hand-edit"
# is the human-visible + machine-checked signal that this tree is regenerated, never authored.
DERIVED_MARKER = "generated by tools.harness_emit — do not hand-edit"


class HarnessEmitError(RuntimeError):
    """Loud-fail: a cap/shape violation or a path escaping the harness lane (cf. DocsSyncError)."""


# --- path confinement (mirror docs_sync._confine, VERBATIM — T-07-01) -------------------------


def _confine(path: Path, base: Path) -> Path:
    """Resolve ``path`` and refuse it unless it stays under ``base`` (no traversal outside)."""
    resolved = path.resolve()
    base_resolved = Path(base).resolve()
    if base_resolved != resolved and base_resolved not in resolved.parents:
        raise HarnessEmitError(f"emitted path escapes harness confinement: {resolved}")
    return resolved


# --- deterministic frontmatter serialization (fixed order, no round-trip) ----------------------

# A key is emitted plain when it is a simple slug-ish token; anything else (a bash glob like ``*``
# or ``uv *``) is double-quoted so the YAML stays valid and stable.
_PLAIN_KEY = re.compile(r"^[A-Za-z0-9_-]+$")
# A scalar VALUE is emitted plain when it is a safe unquoted YAML token (letters/digits + a small
# set of inner punctuation, e.g. ``allow``, ``subagent``, ``provider/explorer-tier``,
# ``Read, Edit, Bash``). Anything else falls back to a double-quoted scalar.
_PLAIN_VALUE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9 _./,*+-]*$")


def _dquote(text: str) -> str:
    """Double-quote a scalar with the minimal YAML escaping (backslash + quote)."""
    escaped = text.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _fold(text: str) -> str:
    """Collapse every run of whitespace (incl. newlines from a ``>-`` block) to one space; strip."""
    return " ".join(str(text).split())


def _emit_key(key: str) -> str:
    return key if _PLAIN_KEY.match(str(key)) else _dquote(str(key))


def _emit_scalar(key: str, value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    text = str(value)
    # A description is a routing paragraph (authored as a folded ``>-`` block) — always fold to one
    # line and quote, so multi-line source never perturbs the byte output.
    if key == "description":
        return _dquote(_fold(text))
    if _PLAIN_VALUE.match(text) and not text.endswith(" "):
        return text
    return _dquote(text)


def _emit_entry(key: str, value: object, indent: int) -> list[str]:
    pad = "  " * indent
    ky = _emit_key(key)
    if isinstance(value, dict):
        lines = [f"{pad}{ky}:"]
        for sub_key, sub_value in value.items():  # AUTHORED order preserved (bash last-wins, P3)
            lines.extend(_emit_entry(sub_key, sub_value, indent + 1))
        return lines
    return [f"{pad}{ky}: {_emit_scalar(key, value)}"]


def render_markdown(projected_fm: dict, body: str) -> str:
    """Render one projected artifact to a deterministic ``.md`` (marker + frontmatter + body).

    Generic across artifact types (agents, commands, skills): the frontmatter dict is already
    projected to its per-runtime shape and fixed key order; this only serializes it. Layout: ``---``
    fence, the DERIVED YAML-comment marker, the projected frontmatter in order, the closing ``---``,
    a blank line, then the body normalized to LF with a single trailing newline. No timestamp/float,
    so re-render is byte-identical (the CI ``emit-drift`` gate depends on it).
    """
    lines = ["---", f"# {DERIVED_MARKER}"]
    for key, value in projected_fm.items():
        lines.extend(_emit_entry(key, value, 0))
    lines.append("---")
    body_norm = body.replace("\r\n", "\n").replace("\r", "\n").strip("\n")
    lines.extend(["", body_norm])
    return "\n".join(lines).rstrip("\n") + "\n"


# Backward-compatible alias — the agent walking skeleton (07-01) named this ``render_agent``; the
# serializer is artifact-neutral, so commands/skills reuse it under its generic name.
render_agent = render_markdown


# --- discovery --------------------------------------------------------------------------------


def iter_agents(agents_dir: str | Path) -> list[tuple[str, dict, str]]:
    """Yield ``(name, frontmatter, body)`` for every ``agents/*.md``, sorted by path.

    The glob is NON-recursive so ``agents/templates/*.md`` (persona scaffolds, not emitted personas)
    are excluded. Frontmatter is read via the shared ``parse_frontmatter`` — never re-slice fences.
    """
    root = Path(agents_dir)
    result: list[tuple[str, dict, str]] = []
    for path in sorted(root.glob("*.md")):
        fm, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        result.append((path.stem, fm, body))
    return result


def iter_commands(commands_dir: str | Path) -> list[tuple[str, dict, str]]:
    """Yield ``(name, frontmatter, body)`` for every ``commands/*.md``, sorted by path.

    The glob is NON-recursive (top-level ``*.md`` only). Frontmatter is read via the shared
    ``parse_frontmatter``; the ``` !`shell` ``` + ``$ARGUMENTS`` body is returned unchanged and is
    shared verbatim by BOTH runtime projections.
    """
    root = Path(commands_dir)
    result: list[tuple[str, dict, str]] = []
    for path in sorted(root.glob("*.md")):
        fm, body = parse_frontmatter(path.read_text(encoding="utf-8"))
        result.append((path.stem, fm, body))
    return result


def iter_plugins(plugins_dir: str | Path) -> list[Path]:
    """Yield each ``plugins/*.ts`` source path, sorted by name.

    The ``.ts`` is authored source consumed by the opencode RUNTIME (deferred), not the emitter:
    it is copied BYTE-FOR-BYTE (``read_bytes``/``write_bytes``) and is NEVER parsed, transformed,
    re-serialized, imported, or executed at emit (D-01; Elevation mitigation T-07-04). No DERIVED
    marker is injected — it is verbatim source, not generated Markdown.
    """
    return sorted(Path(plugins_dir).glob("*.ts"))


def iter_skills(skills_dir: str | Path) -> list[tuple[str, dict, str, Path]]:
    """Yield ``(name, frontmatter, body, skill_dir)`` for every ``skills/<name>/SKILL.md``, sorted.

    ``skill_dir`` is the skill's source dir so the emitter can find its ``references/`` subtree.
    ``name`` is the directory name (== the frontmatter ``name``, enforced by the validator).
    """
    root = Path(skills_dir)
    result: list[tuple[str, dict, str, Path]] = []
    for skill_md in sorted(root.glob("*/SKILL.md")):
        fm, body = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        result.append((skill_md.parent.name, fm, body, skill_md.parent))
    return result


# --- opencode.json config (the one genuine transform: matrix → 15-key permission block) -------


def build_opencode_config(harness_dir: str | Path = HARNESS_DIR) -> dict:
    """Build the emitter-owned root ``opencode.json`` = authored config + full 15-key permission.

    The emitter OWNS ``opencode.json`` wholesale: it starts from authored ``harness/opencode.json``
    (model tiers, formatter, instructions, mcp, plugin) and REPLACES its PARTIAL ``permission``
    block with the full 15-key block projected from ``harness/permission-matrix.json``
    (:func:`permissions.build_permission_block` strips ``_note`` + ``path_deny_globs``). Every other
    authored key passes through verbatim. Serialize with :func:`permissions.dumps_config`.
    """
    harness_dir = Path(harness_dir)
    config = json.loads((harness_dir / "opencode.json").read_text(encoding="utf-8"))
    matrix = load_matrix(harness_dir / "permission-matrix.json")
    config["permission"] = permissions.build_permission_block(matrix)
    return config


# --- emit -------------------------------------------------------------------------------------


def emit(
    harness_dir: str | Path = HARNESS_DIR,
    opencode_dir: str | Path = OPENCODE_DIR,
    claude_dir: str | Path = CLAUDE_DIR,
    manifest_path: str | Path = MANIFEST_PATH,
    root: str | Path = REPO_ROOT,
) -> list[Path]:
    """Emit the harness agents + commands + skills to BOTH runtime trees; return the written paths.

    VALIDATE-THEN-WRITE (loud-fail): every source artifact and its projection(s) are validated
    BEFORE any file is written, so a cap/shape violation anywhere aborts having written nothing.
    Each target path is ``_confine``d before writing (incl. every recursive ``references/`` copy).
    Finally the ownership manifest is prune-then-written (the manifest path is excluded from the
    returned list).
    """
    harness_dir = Path(harness_dir)

    # --- validate EVERYTHING up front (write nothing on any failure) ---
    agent_plan: list[tuple[str, dict, dict, str]] = []
    for name, fm, body in iter_agents(harness_dir / "agents"):
        validate.check_agent(name, fm)
        opencode_fm = project_agent.to_opencode(fm)
        claude_fm = project_agent.to_claude(fm)
        validate.check_projections(name, opencode_fm, claude_fm)
        agent_plan.append((name, opencode_fm, claude_fm, body))

    command_plan: list[tuple[str, dict, dict, str]] = []
    for name, fm, body in iter_commands(harness_dir / "commands"):
        validate.check_command(name, fm)
        opencode_fm = project_command.to_opencode(fm)
        claude_fm = project_command.to_claude(fm)
        command_plan.append((name, opencode_fm, claude_fm, body))

    skill_plan: list[tuple[str, dict, str, Path]] = []
    skills = iter_skills(harness_dir / "skills")
    for name, fm, body, skill_dir in skills:
        validate.check_skill(name, fm, body)
        skill_plan.append((name, project_skill.project(fm), body, skill_dir))
    if skills:  # anti-drift: the emitted set must equal EXPECTED_SKILLS exactly (real tree = 9)
        validate.check_skill_set({name for name, _, _, _ in skills})

    # opencode.json — the one genuine transform. Build + validate BEFORE any write (loud-fail):
    # a schema-invalid config or a leaked real model id aborts having written nothing (T-07-07/03).
    opencode_config = build_opencode_config(harness_dir)
    config_schema = json.loads(
        (harness_dir / "opencode.config.schema.json").read_text(encoding="utf-8")
    )
    validate.check_opencode_config(opencode_config, config_schema)

    # --- write both trees ---
    written: list[Path] = []

    opencode_agent_dir = Path(opencode_dir) / "agent"
    claude_agent_dir = Path(claude_dir) / "agents"
    opencode_agent_dir.mkdir(parents=True, exist_ok=True)
    claude_agent_dir.mkdir(parents=True, exist_ok=True)
    for name, opencode_fm, claude_fm, body in agent_plan:
        opencode_target = _confine(opencode_agent_dir / f"{name}.md", opencode_agent_dir)
        claude_target = _confine(claude_agent_dir / f"{name}.md", claude_agent_dir)
        opencode_target.write_text(render_markdown(opencode_fm, body), encoding="utf-8")
        claude_target.write_text(render_markdown(claude_fm, body), encoding="utf-8")
        written.extend((opencode_target, claude_target))

    if command_plan:
        opencode_command_dir = Path(opencode_dir) / "command"
        claude_command_dir = Path(claude_dir) / "commands"
        opencode_command_dir.mkdir(parents=True, exist_ok=True)
        claude_command_dir.mkdir(parents=True, exist_ok=True)
        for name, opencode_fm, claude_fm, body in command_plan:
            opencode_target = _confine(opencode_command_dir / f"{name}.md", opencode_command_dir)
            claude_target = _confine(claude_command_dir / f"{name}.md", claude_command_dir)
            opencode_target.write_text(render_markdown(opencode_fm, body), encoding="utf-8")
            claude_target.write_text(render_markdown(claude_fm, body), encoding="utf-8")
            written.extend((opencode_target, claude_target))

    if skill_plan:
        opencode_skill_root = Path(opencode_dir) / "skill"
        claude_skill_root = Path(claude_dir) / "skills"
        for name, projected_fm, body, skill_dir in skill_plan:
            opencode_dir_ = opencode_skill_root / name
            claude_dir_ = claude_skill_root / name
            opencode_dir_.mkdir(parents=True, exist_ok=True)
            claude_dir_.mkdir(parents=True, exist_ok=True)
            opencode_skill = _confine(opencode_dir_ / "SKILL.md", opencode_dir_)
            claude_skill = _confine(claude_dir_ / "SKILL.md", claude_dir_)
            rendered = render_markdown(projected_fm, body)
            opencode_skill.write_text(rendered, encoding="utf-8")
            claude_skill.write_text(rendered, encoding="utf-8")
            written.extend((opencode_skill, claude_skill))
            # references/** — copied BYTE-FOR-BYTE to both trees (no normalize), each _confine'd.
            for rel in project_skill.iter_reference_files(skill_dir / "references"):
                data = (skill_dir / "references" / rel).read_bytes()
                for dest_root in (opencode_dir_, claude_dir_):
                    dest_refs = dest_root / "references"
                    dest = _confine(dest_refs / rel, dest_refs)
                    dest.parent.mkdir(parents=True, exist_ok=True)
                    dest.write_bytes(data)
                    written.append(dest)

    # --- plugins: 5 .ts copied BYTE-FOR-BYTE to .opencode/plugin (D-01; NEVER parsed/executed) ---
    # The one Elevation-risk surface (T-07-04): the .ts is read as bytes and written as bytes — the
    # emitter never parses/imports/executes it (execution is opencode-runtime, deferred). There is
    # NO Claude plugin target (Claude uses settings.json hooks) and NO .opencode/tool/ dir (no src).
    plugins = iter_plugins(harness_dir / "plugins")
    if plugins:
        opencode_plugin_dir = Path(opencode_dir) / "plugin"
        opencode_plugin_dir.mkdir(parents=True, exist_ok=True)
        for plugin in plugins:
            data = plugin.read_bytes()  # bytes in → bytes out; no parse/transform/execute (T-07-04)
            target = _confine(opencode_plugin_dir / plugin.name, opencode_plugin_dir)
            target.write_bytes(data)
            written.append(target)

    # --- root opencode.json (emitter-owned wholesale; opencode's documented project-config path) --
    config_target = _confine(Path(root) / "opencode.json", Path(root))
    config_target.write_text(permissions.dumps_config(opencode_config), encoding="utf-8")
    written.append(config_target)

    # --- ownership manifest (prune stale, write current) ---
    manifest.prune_then_write(written, manifest_path=manifest_path, root=Path(root))
    return written


def main(argv: list[str] | None = None) -> int:
    """CLI: emit harness agents + commands + skills to ``.opencode/`` + ``.claude/`` + manifest."""
    argv = sys.argv[1:] if argv is None else argv  # noqa: F841 (reserved for future flags)
    written = emit()
    for path in written:
        try:
            rel = path.relative_to(REPO_ROOT)
        except ValueError:
            rel = path
        print(f"wrote {rel}")
    print(
        f"harness-emit: {len(written)} artifact(s) emitted to "
        f".opencode/ + .claude/ + opencode.json (agents + commands + skills + plugins + config)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
