"""Regime B-md — idempotent managed-block splice into shared human/GSD Markdown files (EMIT-02).

Root ``AGENTS.md`` and ``CLAUDE.md`` are SHARED files: they carry a GSD-managed ``## Project`` block,
nearest-wins rules, and human prose (Phases 2/5). The emitter must own ONLY a fenced managed block
and preserve everything else verbatim, or it breaks the operating rules the repo runs on
(threat T-07-02). This is deliberately NOT a whole-file write (Regime A / the ownership manifest) —
it is a two-marker string splice with no external "managed block" dependency.

Contract of :func:`splice_managed_block`:
  * markers PRESENT → replace ONLY the content between them; text before/after is byte-preserved.
  * markers ABSENT → append the fenced block exactly once; a second call is byte-identical.
  * exactly ONE marker → ambiguous/corrupt input → raise ``ValueError`` (fail loud, never guess).
  * output is normalized to LF, BOM-stripped, with a single trailing newline (§4.3 discipline).

The caller (``tools.harness_emit.generate``) builds a DETERMINISTIC ``block_body`` (sorted content,
no ``datetime.now()``/floats) so re-emit is byte-identical and the CI ``emit-drift`` gate stays
clean on these shared files. If a human hand-edits INSIDE the block, re-emit overwrites it → dirty
diff → the gate catches it; an edit OUTSIDE the block is preserved → clean diff (the whole point).
"""

from __future__ import annotations

#: The HTML-comment fence (invisible when the Markdown is rendered). RESEARCH §Regime B.
BEGIN_MARKER = "<!-- BEGIN HARNESS-MANAGED (generated by tools.harness_emit — do not hand-edit) -->"
END_MARKER = "<!-- END HARNESS-MANAGED -->"


def _normalize(text: str) -> str:
    """Strip a UTF-8 BOM and force LF line endings (§4.3 canonicalization)."""
    if text.startswith("﻿"):
        text = text[1:]
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _finalize(text: str) -> str:
    """Collapse any trailing blank lines to exactly one trailing newline."""
    return text.rstrip("\n") + "\n"


def splice_managed_block(existing_text: str, block_body: str) -> str:
    """Splice ``block_body`` into ``existing_text`` between the HARNESS-MANAGED markers.

    See the module docstring for the full contract. ``block_body`` is normalized and stripped of
    surrounding blank lines so the emitter controls the exact spacing inside the fence; the returned
    document is LF, BOM-free, single-trailing-newline.
    """
    existing = _normalize(existing_text)
    body = _normalize(block_body).strip("\n")
    block = f"{BEGIN_MARKER}\n{body}\n{END_MARKER}"

    begin_idx = existing.find(BEGIN_MARKER)
    end_idx = existing.find(END_MARKER)

    if begin_idx != -1 and end_idx != -1 and end_idx > begin_idx:
        # Markers present → replace ONLY the fenced region, preserve before/after verbatim.
        before = existing[:begin_idx]
        after = existing[end_idx + len(END_MARKER) :]
        return _finalize(before + block + after)

    if begin_idx == -1 and end_idx == -1:
        # Markers absent → append the block exactly once (idempotent thereafter).
        base = existing.rstrip("\n")
        merged = f"{base}\n\n{block}" if base else block
        return _finalize(merged)

    # Exactly one marker (or END before BEGIN) → malformed; refuse rather than corrupt the file.
    raise ValueError(
        "malformed HARNESS-MANAGED fence: exactly one marker present "
        "(need both BEGIN and END, in order, or neither)"
    )
