"""Regime B-md — idempotent managed-block splice into shared human/GSD Markdown files (EMIT-02).

Root ``AGENTS.md`` and ``CLAUDE.md`` are SHARED files: they carry a GSD-managed ``## Project`` block,
nearest-wins rules, and human prose (Phases 2/5). The emitter must own ONLY a fenced managed block
and preserve everything else verbatim, or it breaks the operating rules the repo runs on
(threat T-07-02). This is deliberately NOT a whole-file write (Regime A / the ownership manifest) —
it is a two-marker string splice with no external "managed block" dependency.

Contract of :func:`splice_managed_block`:
  * markers PRESENT → replace ONLY the content between them; text before/after is byte-preserved.
  * markers ABSENT → append the fenced block exactly once; a second call is byte-identical.
  * exactly ONE marker → ambiguous/corrupt input → raise ``ValueError`` (fail loud, never guess).
  * output is normalized to LF, BOM-stripped, with a single trailing newline (§4.3 discipline).

The caller (``tools.harness_emit.generate``) builds a DETERMINISTIC ``block_body`` (sorted content,
no ``datetime.now()``/floats) so re-emit is byte-identical and the CI ``emit-drift`` gate stays
clean on these shared files. If a human hand-edits INSIDE the block, re-emit overwrites it → dirty
diff → the gate catches it; an edit OUTSIDE the block is preserved → clean diff (the whole point).
"""

from __future__ import annotations

import copy

#: The HTML-comment fence (invisible when the Markdown is rendered). RESEARCH §Regime B.
BEGIN_MARKER = "<!-- BEGIN HARNESS-MANAGED (generated by tools.harness_emit — do not hand-edit) -->"
END_MARKER = "<!-- END HARNESS-MANAGED -->"


def _normalize(text: str) -> str:
    """Strip a UTF-8 BOM and force LF line endings (§4.3 canonicalization)."""
    if text.startswith("﻿"):
        text = text[1:]
    return text.replace("\r\n", "\n").replace("\r", "\n")


def _finalize(text: str) -> str:
    """Collapse any trailing blank lines to exactly one trailing newline."""
    return text.rstrip("\n") + "\n"


def splice_managed_block(existing_text: str, block_body: str) -> str:
    """Splice ``block_body`` into ``existing_text`` between the HARNESS-MANAGED markers.

    See the module docstring for the full contract. ``block_body`` is normalized and stripped of
    surrounding blank lines so the emitter controls the exact spacing inside the fence; the returned
    document is LF, BOM-free, single-trailing-newline.
    """
    existing = _normalize(existing_text)
    body = _normalize(block_body).strip("\n")
    block = f"{BEGIN_MARKER}\n{body}\n{END_MARKER}"

    begin_idx = existing.find(BEGIN_MARKER)
    end_idx = existing.find(END_MARKER)

    if begin_idx != -1 and end_idx != -1 and end_idx > begin_idx:
        # Markers present → replace ONLY the fenced region, preserve before/after verbatim.
        before = existing[:begin_idx]
        after = existing[end_idx + len(END_MARKER) :]
        return _finalize(before + block + after)

    if begin_idx == -1 and end_idx == -1:
        # Markers absent → append the block exactly once (idempotent thereafter).
        base = existing.rstrip("\n")
        merged = f"{base}\n\n{block}" if base else block
        return _finalize(merged)

    # Exactly one marker (or END before BEGIN) → malformed; refuse rather than corrupt the file.
    raise ValueError(
        "malformed HARNESS-MANAGED fence: exactly one marker present "
        "(need both BEGIN and END, in order, or neither)"
    )


# --- Regime B-json — .claude/settings.json signature-matched, order-preserving hook merge --------
#
# The SECOND (riskiest) merge surface. Unlike AGENTS.md/CLAUDE.md (marker-fenced text splice), this
# is a STRUCTURAL merge of a shared JSON document. The Phase 2/4 harness hooks + the memory-inject
# injector are ALREADY hand-wired into the LIVE .claude/settings.json and guarded by
# tools/memory_regen/tests/test_hook_wiring.py (exactly 4 SessionStart groups). The MVP contract
# (Open Q2 / A5) is IDEMPOTENT COEXISTENCE: reproduce the live file byte-for-byte from the FIRST
# emit — never a 5th SessionStart group (Pitfall 4 / T-07-09), never a global key-sort
# (SessionStart is FIRST / insertion-ordered, not alphabetical — a sort flaps ~274 lines / T-07-11),
# never removing or reordering a GSD hook (T-07-02).

#: The harness-owned hook COMMAND signatures. A hook group whose command contains one of these is
#: owned by the emitter and is append-or-replaced in place; every other group is left verbatim.
HARNESS_SIGNATURES: tuple[str, ...] = (
    "tools.hooks.format_on_write",
    "tools.hooks.contract_guard",
    "tools.hooks.secret_scan",
    "tools.hooks.commit_gate",
    "tools.hooks.resume_gate",
)

#: GSD-owned hook signatures — NEVER removed or reordered (defensive; they never match a harness
#: signature, but this makes the coexistence invariant explicit).
GSD_SIGNATURES: tuple[str, ...] = (
    "gsd-",
    "get-shit-done",
    "memory-inject",
    "tools/bootstrap/install.sh",
)

#: Signatures the harness used to own but no longer emits. A plain signature-set diff (removing a
#: signature from ``HARNESS_SIGNATURES`` alone) is NOT enough to delete its group on re-emit: a
#: group whose command matches no *current* signature falls through as ``sig is None`` and is
#: mistaken for a GSD/human group (kept verbatim forever) — silently defeating a deletion phase's
#: whole point. Listing a signature here makes the retirement an explicit, re-emit-driven removal
#: instead of requiring a hand-edit of the emitted ``.claude/settings.json`` (D-12). Empty until the
#: next PreToolUse-hook deletion phase needs it.
RETIRED_SIGNATURES: tuple[str, ...] = ()

#: The canonical harness hook groups the emitter wires, per event. Key order inside each mapping is
#: AUTHORED (matcher → hooks; type → command → timeout) and MUST match the live committed bytes so
#: an in-place replace reproduces .claude/settings.json exactly. There is NO harness group in
#: SessionStart — all 4 SessionStart slots are GSD/injector-owned (untouched by this merge).
#
#: Every guard command carries a two-clause shell PREFIX (:data:`_GUARD_PREFIX`) so the guard
#: cannot take the whole session down and so a dev session can opt out of the guard wall. It is
#: part of the emitted command string and MUST be reproduced byte-for-byte in .claude/settings.json.
#
#: Clause 1 — ``[ -n "$HARNESS_DEV_LIGHT" ] && exit 0``: a dev session that sets HARNESS_DEV_LIGHT
#: (in the gitignored .claude/settings.local.json) skips the guard entirely. Enforcement then lives
#: where it belongs for this contract-first repo — CI (contract-drift, golden, ruff) and CODEOWNERS
#: at the PR to main — not on every in-editor keystroke. The deployed product and CI leave the flag
#: unset and keep full enforcement.
#
#: Clause 2 — ``python3 tools/harness_lint/workspace_check.py >/dev/null 2>&1 || exit 0``: if the uv
#: workspace cannot resolve (e.g. a tools/* dir was created without its pyproject.toml), EVERY
#: ``uv run`` guard would otherwise die at workspace resolution — before its Python even starts —
#: and, because a failing PreToolUse guard denies its tool, take Read/Write/Bash down repo-wide with
#: the repair locked behind the outage. The bare-python3 workspace check (no uv, no deps) turns that
#: into ALLOW-with-degrade: a guard must fail closed on a real deny, but must NOT block on tooling
#: infrastructure that is not its concern. Proven not to weaken a real deny by the mutation tests in
#: tools/harness_emit/tests/test_guard_prefix.py — a healthy workspace still runs the guard and a
#: constitution write with no bypass still denies.
_GUARD_PREFIX: str = (
    '[ -n "$HARNESS_DEV_LIGHT" ] && exit 0; '
    "python3 tools/harness_lint/workspace_check.py >/dev/null 2>&1 || exit 0; "
)

HARNESS_HOOK_GROUPS: dict[str, list[dict]] = {
    "PostToolUse": [
        {
            "matcher": "Write|Edit",
            "hooks": [
                {
                    "type": "command",
                    "command": _GUARD_PREFIX + "uv run python -m tools.hooks.format_on_write",
                    "timeout": 30,
                }
            ],
        },
    ],
    "PreToolUse": [
        {
            "matcher": "Write|Edit",
            "hooks": [
                {
                    "type": "command",
                    "command": _GUARD_PREFIX + "uv run python -m tools.hooks.contract_guard",
                    "timeout": 10,
                }
            ],
        },
        {
            "matcher": "Read|Write|Edit",
            "hooks": [
                {
                    "type": "command",
                    "command": _GUARD_PREFIX + "uv run python -m tools.hooks.secret_scan",
                    "timeout": 10,
                }
            ],
        },
        {
            "matcher": "Bash",
            "hooks": [
                {
                    "type": "command",
                    "command": (
                        _GUARD_PREFIX + "uv run python -m tools.hooks.commit_gate --from-hook"
                    ),
                    "timeout": 120,
                }
            ],
        },
        {
            "matcher": "Write|Edit|Bash",
            "hooks": [
                {
                    "type": "command",
                    "command": _GUARD_PREFIX + "uv run python -m tools.hooks.resume_gate",
                    "timeout": 15,
                }
            ],
        },
    ],
}


def _group_signature(group: dict, signatures: tuple[str, ...]) -> str | None:
    """Return the FIRST signature in ``signatures`` matched by any command in ``group``, else None."""
    for hook in group.get("hooks", []):
        command = hook.get("command", "")
        for sig in signatures:
            if sig in command:
                return sig
    return None


def merge_settings(
    existing: dict,
    harness_signatures: tuple[str, ...] = HARNESS_SIGNATURES,
    harness_groups: dict[str, list[dict]] = HARNESS_HOOK_GROUPS,
    retired_signatures: tuple[str, ...] = RETIRED_SIGNATURES,
) -> dict:
    """Merge the harness hook groups into ``existing`` settings IN PLACE, order-preserving (Regime B-json).

    For each event in ``harness_groups`` the desired harness group (identified by its command
    signature) is APPENDED-OR-REPLACED where it already appears — never duplicated, never sorted,
    never moved. GSD/human groups (no harness signature) are kept verbatim in their live position;
    a second harness group matching an already-placed signature is DROPPED (de-dup → no double-wire).
    A harness group absent from ``existing`` is appended at the tail of its event list. A group
    matching a ``retired_signatures`` entry is DROPPED outright — it is a formerly harness-owned
    group whose signature was deliberately removed (a deletion phase), not a GSD/human group.

    Because the Phase 2/4 hooks are ALREADY committed in the live order, calling this on the parsed
    live ``.claude/settings.json`` reproduces it byte-for-byte from the FIRST emit (serialize with
    ``json.dumps(merged, indent=2, ensure_ascii=False) + "\\n"`` — NO ``sort_keys``). The input is
    not mutated; a deep copy is returned.
    """
    merged = copy.deepcopy(existing)
    hooks = merged.setdefault("hooks", {})

    for event, desired_groups in harness_groups.items():
        existing_groups = hooks.get(event, [])
        # Map each desired harness group to the signature it carries, preserving authored order.
        desired_by_sig: dict[str, dict] = {}
        desired_order: list[str] = []
        for group in desired_groups:
            sig = _group_signature(group, harness_signatures)
            if sig is None:  # pragma: no cover — HARNESS_HOOK_GROUPS always carries a signature
                continue
            desired_by_sig[sig] = group
            desired_order.append(sig)

        result: list[dict] = []
        placed: set[str] = set()
        for group in existing_groups:
            sig = _group_signature(group, harness_signatures)
            if sig is None:
                if _group_signature(group, retired_signatures) is not None:
                    # A retired harness group — drop it, this is the deletion path (D-12).
                    continue
                # GSD/human group — keep verbatim, in place, never removed/reordered (T-07-02).
                result.append(group)
            elif sig in desired_by_sig:
                if sig not in placed:
                    # Replace the harness group in place with the canonical definition.
                    result.append(copy.deepcopy(desired_by_sig[sig]))
                    placed.add(sig)
                # else: a duplicate harness group — DROP it (de-dup, no double-wire / Pitfall 4).
            else:
                # A harness-signature group we don't own the canonical form of — keep verbatim.
                result.append(group)

        # Append any desired harness group not already present (first-time wiring at the tail).
        for sig in desired_order:
            if sig not in placed:
                result.append(copy.deepcopy(desired_by_sig[sig]))
                placed.add(sig)

        # Only touch the event list if the harness actually owns groups there (keeps the key in its
        # live insertion position — reassigning an existing key never moves it).
        if event in hooks or result:
            hooks[event] = result

    return merged
