"""DOCSUP-06 drafting exclusions — the five classes ``/docs-update`` must never draft into.

**The import IS the control (D-06).** Every glob list below is IMPORTED from its existing home and
never retyped, so deleting a glob at its home turns named rows in ``tests/test_exclusions.py`` RED
repo-wide. ``tests`` pins that with ``is``-identity assertions, not ``==``: a locally retyped copy
would keep every monkeypatch proof green while the "delete at the home and this fails" claim
silently became false (Phase 28 CR-02).

Normalization is copied from ``refuse_unsafe_destination`` (``tools/adoption_apply/apply.py``) —
resolved path, root-relative, lowering the CANDIDATE only and never the globs (``resolve_path`` is
``fnmatchcase``, i.e. case-SENSITIVE, which is exactly why the candidate is lowered). Without that,
27.1's CR-01 (``./contracts/x``, ``CONTRACTS/x``, a symlink resolving onto the plane) replays
verbatim on this new surface.

ONE deliberate divergence from ``refuse_unsafe_destination``: a literal ``..`` segment is NOT
pre-rejected. That function guards a WRITE and may refuse early; this is a CLASSIFIER, and
``docs/../contracts/x`` is a legal spelling of a constitution path that must classify rather than
error. Confinement is not weakened — ``refuse_if_outside_root`` runs on the RESOLVED path, so a
genuine escape is still caught.

Refusal-to-draft is expressed by the RETURN VALUE, not by raising: this is a classifier consumed by
a command, and an exception would force call sites into ``try``/``except`` and invite one to swallow
it. The single asymmetry is a target that leaves the repo root (or an absolute target): that is not
"no exclusion applies", it is malformed input, and it raises :class:`PathEscapeError`. A classifier
that answered ``None`` to a path leaving the repo would be 27.1 CR-01 on a new surface.

Purity: path-shaped only, no file CONTENT is read. In particular this does NOT re-read an ADR's
``Status:`` line the way ``registry._adr_status`` does — ``registry.py`` already refuses a
non-accepted ADR as a binding target at LOAD time, so by the time ``/docs-update`` holds a binding
the ADR is accepted; re-reading content inside a path predicate would make the function impure and
I/O-dependent for no added control.

Layering: ``tools/hooks/contract_guard.py`` and the matrix ``path_deny_globs`` remain the runtime
WRITE-side backstops. This module is the DECISION layer — it tells a command not to draft; it does
not replace the gates that stop the write.
"""

from __future__ import annotations

from pathlib import Path

from tools.adoption_apply.apply import PathEscapeError, refuse_if_outside_root
from tools.adoption_scan.destinations import DERIVED_GLOBS
from tools.docs_guard.registry import ADR_GLOBS, REPO_ROOT
from tools.harness_perms import resolve_path
from tools.hooks.contract_guard import CONSTITUTION_GLOBS

# Stable machine-readable reasons. Distinct per class because the REMEDIATION differs: an accepted
# ADR is superseded via /adr and never edited in place, a constitution file goes through
# /golden-approve + CODEOWNERS, and a derived file is regenerated by its emitter.
REASON_CONSTITUTION = "constitution-plane"
REASON_DERIVED = "derived-plane"
REASON_ACCEPTED_ADR = "accepted-adr"

__all__ = [
    "ADR_GLOBS",
    "CONSTITUTION_GLOBS",
    "DERIVED_GLOBS",
    "REASON_ACCEPTED_ADR",
    "REASON_CONSTITUTION",
    "REASON_DERIVED",
    "exclusion_reason",
]


def _relative_candidate(target: str, root: Path) -> str:
    """Resolve ``root / target``, confine it, and return the lowered root-relative POSIX path.

    Raises :class:`PathEscapeError` for an absolute target (``Path(root) / "/etc/passwd"`` silently
    discards ``root``) and, via ``refuse_if_outside_root``, for one that resolves out of the root.
    """
    if Path(target).is_absolute():
        raise PathEscapeError(
            f"'{target}' is an absolute path — an exclusion target is named relative to the repo "
            "root, and joining an absolute path would silently discard that root."
        )
    resolved_root = Path(root).resolve()
    resolved = (resolved_root / target).resolve(strict=False)
    refuse_if_outside_root(resolved, resolved_root)
    return resolved.relative_to(resolved_root).as_posix().lower()


def exclusion_reason(target: str, root: Path = REPO_ROOT) -> str | None:
    """Return why ``target`` is excluded from human-doc drafting, or ``None`` if it is draftable.

    Exactly one of :data:`REASON_ACCEPTED_ADR`, :data:`REASON_DERIVED`,
    :data:`REASON_CONSTITUTION`, or ``None``. The ADR class is checked FIRST so a ``docs/adr/**``
    target never collapses into the generic constitution reason, losing its supersede-don't-edit
    remediation.

    The three glob lists are read as MODULE ATTRIBUTES at call time (never frozen into a default
    argument) so the per-class deletion proofs in ``tests/test_exclusions.py`` bite.
    """
    candidate = _relative_candidate(target, root)
    if resolve_path(ADR_GLOBS, candidate) == "deny":
        return REASON_ACCEPTED_ADR
    if resolve_path(DERIVED_GLOBS, candidate) == "deny":
        return REASON_DERIVED
    if resolve_path(CONSTITUTION_GLOBS, candidate) == "deny":
        return REASON_CONSTITUTION
    return None
